version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run:
          name: js lint
          command: git diff --name-only --diff-filter=ACMR origin/dev..origin/${CIRCLE_BRANCH} -- '*.js' | xargs -r npx eslint
